# unforgettable7_game/unforgettable7_common/Makefile.toml
# https://github.com/sagiegurari/cargo-make


[config]
skip_core_tasks = true

[tasks.default]
description = "help for prepared make tasks"
clear = true
script= [
"echo ",
"echo COMMANDS AND MAKE TASKS:",
"echo ",
"echo $ clear - clear the screen",
"echo $ cargo make - this list",
"echo ",
"echo ",
"echo $ cargo make check - check code errors without compiling",
"echo $ cargo make release - build release version, increment semver patch in Cargo.toml",
"echo ",
"echo $ cargo make test - test the test code",
"echo $ cargo make udeps - cargo +nightly udeps - unused dependencies",
"echo $ cargo crev verify - always verify you dependencies",
"echo $ cargo make audit - RustSec advisories",
"echo $ cargo make doc - includes from Cargo.toml to README.md and from README.md to main.rs or lib.rs, generates doc and copies to docs folder, exports codetour to .md.",
"echo ",
"echo $ cargo make publish_to_web",
"echo ",
]

# end of help
# end of help
# end of help

[tasks.check]
description = "cargo check --release"
clear = true
script = [
    "echo $ cargo fmt",
    "cargo fmt",
    "echo $ cargo check --release",
    "cargo check --release",
]

# end of dev scripts
# end of dev scripts
# end of dev scripts

[tasks.release]
description = "cargo build release"
clear = true
script = [
    # Binaries version is date
    "echo $ lmake_version_from_date",
    "lmake_version_from_date",
    "echo $ cargo fmt",
    "cargo fmt",
    "echo $ cargo build --release",
    "cargo build --release",
]

# end of release scripts
# end of release scripts
# end of release scripts

[tasks.test]
description = "cargo test"
clear = true
script = [
    "echo $ cargo test",
    "cargo test",
]

[tasks.udeps]
description = "lists unused dependencies needs nightly"
clear = true
script = [
	"cargo +nightly udeps",
]

[tasks.verify]
description = "cargo crev verify - "
clear = true
script = [
    "cargo crev verify"
]

[tasks.audit]
description = "cargo audit - RustSec advisories"
clear = true
script = [
    "cargo audit"
]

[tasks.doc]
description = "cargo doc - create docs from doc comments"
clear = true
script= [
    "echo $ lmake_lines_of_code",
    "lmake_lines_of_code",
    "echo $ lmake_cargo_toml_to_md",
    "lmake_cargo_toml_to_md",
    "echo $ lmake_md_to_doc_comments",
    "lmake_md_to_doc_comments",
    "echo $ cargo doc --no-deps --document-private-items",
    # create doc from doc comments
    "cargo doc --no-deps --document-private-items",
    "echo $ codetour_export_to_md",
    # export code tour to md
    "codetour_export_to_md",
    # message to help user with next move
    "echo after successful doc, run cargo make commit msg_for_commit",
]

# end of git script
# end of git script
# end of git script

# end of publish script
# end of publish script
# end of publish script
